#include <iostream>

//Problem 2:
//Each new term in the Fibonacci sequence is generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be :
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even - valued terms.

unsigned long long fibonacci(unsigned long long n);

unsigned long long fibonacci(unsigned long long n) {
	if (n <= 0)
		return 0;
	else if (n == 1)
		return 1;
	return fibonacci(n - 1) + fibonacci(n - 2);
}


int main() {

	unsigned i{ 0 };
	int sum{ 0 };

	do {
		std::cout << fibonacci(++i) << " ";

		if (fibonacci(i) % 2 == 0)
			sum += fibonacci(i);

	} while (fibonacci(i+1) <= 4000000);

	std::cout << "\n \nsum is " << sum << std::endl;

return 0;
};